steps:
  - name: ":docker: :package:"
    plugins:
      docker-compose#v2.2.0:
        build: fusion-orchestrate
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - name: ":eslint:"
    command: "yarn lint"
    plugins:
      docker-compose#v2.2.0:
        run: fusion-orchestrate
    agents:
      queue: workers
