steps:
  - name: ":docker: :package:"
    plugins:
      docker-compose#v2.5.0:
        build: fusion-orchestrate
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - name: ":gear:"
    command: "./bin/cli.js enforceSettings"
    plugins:
      docker-compose#v2.5.0:
        run: fusion-orchestrate
    agents:
      queue: workers
